mqtt_server: ''
mqtt_port: ''
mqtt_user: ''
mqtt_password: ''
mqtt_topic: 'stib'
stib_api_key: 'secret'
lang: 'fr'
message_lang: 'fr'
stops:
  - stop_id: 12345
    line_numbers:
      - 12
      - 34
  - stop_id: 5219
    line_numbers:
      - 54
      - 12
      - 74
