mqtt_server: 'my.mqttserv.er'
mqtt_port: '1883'
mqtt_user: 'username'
mqtt_password: 'password'
mqtt_topic: 'stib'

stib_api_key: 'a1b2c3d4e5f6g7h8' # https://data.stib-mivb.be/account/api-keys/
lang: 'fr' # fr or nl
message_lang: 'fr' # fr, nl, or en

# https://www.stib-mivb.be/horaires-dienstregeling2.html?l=fr&_line=T82&_directioncode=V&_stop=3194
stops:
  - stop_id: 3194
    line_numbers:
      - 50
      - T82
  - stop_id: 5219
    line_numbers:
      - 54
      - 97
      - 74
